services:
  - type: web
    name: girona_fc_api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d24palili9vc73ehqdn0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: girona_db
      - key: DB_USERNAME
        value: girona_user
      - key: DB_PASSWORD
        value: eeqJGisowxtO8vq3VjWXqsH9Uc32aNAh
